[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
solc_version = "0.8.30"
evm_version = "prague"

gas_reports = ["*"]

[lint]
exclude_lints = ["mixed-case-variable", "mixed-case-function", "pascal-case-struct"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://reth-ethereum.ithaca.xyz/rpc"